### ISSUE TITLE
Build fails with latest ruby

### ISSUE THREAD

**Issue by alexandrevicenzi** [openSUSE/news-o-o#196]
Hi,

The project fails to build on Ruby 3.3 but works fine on 3.2.

```
root@777b5b1b45c0:/src# bundle exec jekyll build
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/local/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level
                   ^^^^^^^^^^^^^^^
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:27:in `process'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `each'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /src/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /src/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /src/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /src/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /src/vendor/bundle/ruby/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /src/vendor/bundle/ruby/3.3.0/gems/jekyll-4.3.2/exe/jekyll:15:in `<top (required)>'
	from /src/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /src/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `load'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli/exec.rb:23:in `run'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:491:in `exec'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:34:in `dispatch'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/cli.rb:28:in `start'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/exe/bundle:45:in `block in <top (required)>'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /src/vendor/bundle/ruby/3.3.0/gems/bundler-2.4.6/exe/bundle:33:in `<top (required)>'
	from /usr/local/bin/bundle:25:in `load'
	from /usr/local/bin/bundle:25:in `<main>'
root@777b5b1b45c0:/src# ruby --version
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
root@777b5b1b45c0:/src# exit
exit
```

**Comment by ddemaio** [comment]
environment has been update
